[package]
name = "foreign-types-shared"
version = "0.2.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "An internal crate used by foreign-types"
repository = "https://github.com/sfackler/foreign-types"

[dependencies]
select-rustc = "0.1"
