[package]
name = "foreign-types"
version = "0.4.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A framework for Rust wrappers over C APIs"
repository = "https://github.com/sfackler/foreign-types"
readme = "README.md"

[features]
default = ["std"]
std = ["foreign-types-macros/std"]

[dependencies]
select-rustc = "0.1"

foreign-types-macros = { version = "0.1", path = "../foreign-types-macros" }
foreign-types-shared = { version = "0.2", path = "../foreign-types-shared" }
